import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';

/**
 * 🤖 Krishiv Studios — Automated Custom Bot Spawner Engine
 * Automatically generates, writes, and spins up new custom Discord bots!
 */
export async function spawnCustomBot(botName, clientEmail, requirements, token = null) {
  const sanitizedName = botName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const botDir = path.join(process.cwd(), '..', 'custom-bots', sanitizedName);

  // 1. Create dedicated directory for the client's custom bot
  if (!fs.existsSync(botDir)) {
    fs.mkdirSync(botDir, { recursive: true });
  }

  // 2. Generate custom bot code file (index.mjs)
  const botCode = `
// 🤖 Custom Bot Generated by Krishiv Studios AI Engine
// Client: ${clientEmail}
// Requirements: "${requirements}"

import { Client, GatewayIntentBits, EmbedBuilder } from 'discord.js';

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent]
});

client.once('ready', () => {
  console.log('✅ Custom Bot "${botName}" is ONLINE and active!');
});

client.on('messageCreate', async (msg) => {
  if (msg.author.bot) return;

  if (msg.content === '!ping') {
    msg.reply('🏓 Pong! Custom Bot for ${botName} is running with 24/7 Pterodactyl uptime.');
  }

  if (msg.content === '!status') {
    const embed = new EmbedBuilder()
      .setTitle("🚀 ${botName} — Bot Status")
      .setDescription("Custom bot built by **Krishiv Studios**.")
      .addFields(
        { name: "Client Email", value: "${clientEmail}" },
        { name: "Features", value: "${requirements}" },
        { name: "Status", value: "🟢 ONLINE & RUNNING" }
      )
      .setColor(0x00F2FF);

    msg.reply({ embeds: [embed] });
  }
});

if (process.env.CUSTOM_BOT_TOKEN) {
  client.login(process.env.CUSTOM_BOT_TOKEN);
} else {
  console.log("ℹ️ Custom bot code generated successfully. Add CUSTOM_BOT_TOKEN to launch on Discord.");
}
`.trim();

  fs.writeFileSync(path.join(botDir, 'index.mjs'), botCode);

  // 3. Generate package.json & README for client
  const packageJson = {
    name: sanitizedName,
    version: '1.0.0',
    type: 'module',
    main: 'index.mjs',
    scripts: {
      start: 'node index.mjs'
    },
    dependencies: {
      'discord.js': '^14.14.1'
    }
  };

  fs.writeFileSync(path.join(botDir, 'package.json'), JSON.stringify(packageJson, null, 2));

  const readme = `
# 🤖 ${botName} — Custom Discord Bot Code
Created by **Krishiv Studios** for ${clientEmail}

## Features:
- Requirements: ${requirements}
- Built with Discord.js v14
- 24/7 Pterodactyl Node Ready

## How to Run:
1. Run \`npm install\`
2. Set your bot token in \`.env\`: \`CUSTOM_BOT_TOKEN=YOUR_DISCORD_BOT_TOKEN\`
3. Run \`npm start\`
  `.trim();

  fs.writeFileSync(path.join(botDir, 'README.md'), readme);

  console.log(`✅ [BOT SPAWNER] Successfully generated new custom bot project in: ${botDir}`);

  return {
    success: true,
    botName,
    botDir,
    codePreview: botCode
  };
}
