# Minecraft server properties
# KryloSMP Season 1 Executive Configuration
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=true
enable-rcon=false
enable-query=true
generator-settings={}
enforce-secure-profile=false
level-name=world
motd=\u00A76\u00A7lKryloSMP \u00A78\u00A7l\u2503 \u00A7e\u00A7lSEASON 1 \u00A77[\u00A7av26.2 Crossplay\u00A77]\n\u00A7f\u00A7l100% KryloCoins Economy \u00A78\u2503 \u00A7d\u00A7ldiscord.gg/6vrEDTu3bx
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=hard
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=true
max-players=1000
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=true
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=\u00A76\u00A7lKryloSMP \u00A78\u2503 \u00A7eClick Yes to load Custom 3D Crates & Keys!
allow-nether=true
server-port=25565
enable-whitelist=false
white-list=false
enforce-whitelist=false
simulation-distance=6
spawn-protection=0
sync-chunk-writes=true
hide-online-players=false
resource-pack=https\://krylosmp-store.web.app/krylosmp-resourcepack.zip
resource-pack-sha1=7dd286c71e87e733dc0ac4d189bf7cdf61d37956
entity-broadcast-range-percentage=100
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=true
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=true
spawn-animals=true
